id: I8631DA0A
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:09:32.786939'
last_modified: '2022-06-18T20:09:32.786951'
parser: null
source_metadata:
  title: Hagiography of the 8th Nālendra abbot mKhyen rab chos rje (1436–1497)
  author: ཞྭ་ལུ་ལོ་ཙཱ་བ་ཆོས་སྐྱོང་བཟང་པོ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2020-06-06);
    revision in process, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:བློ་བཟང་རྒྱལ་མཚན། (Dharamsala) (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:བློ་བཟང་རྒྱལ་མཚན། (Dharamsala) (lg)
  text_witnesses: https://sakyaresearch.org/sources/1799
  bases:
    54eb:
      title: Hagiography of the 8th Nālendra abbot mKhyen rab chos rje (1436–1497)
      order: 1
      base_file: 54eb.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
